// Configurable trigger and schedule layer (WI-032).
//
// A role in .modonome/config.yaml may declare when and how it fires:
//   schedule: { cron, timezone }   a declarative cadence for a scheduled crew role
//   trigger:  <string> | {         how the role is fired
//     type:  schedule | manual | webhook | on-merge | after-role
//     after: [role, ...]           for after-role: run this role after these roles
//     cron:  <string>              an inline cadence shorthand
//   }
//
// This module has two jobs, both pure and dependency-free:
//   1. Runtime ordering. deriveTriggerSequence(cfg) turns after-role declarations into
//      an executed role order, keeping the maker -> checker spine and failing closed on
//      a cycle or a dangling role name. run-cycle.mjs consumes it in resolveRoleSequence.
//   2. Runtime emission. renderScheduleWorkflow(cfg) emits a governed GitHub Actions
//      workflow (.github/workflows/modonome-schedule.yml) that runs each scheduled crew
//      role on its own cadence, so an operator never hand-edits a workflow per agent.
//
// The generated workflow arms nothing by itself: every job defaults to --dry-run and
// only runs --execute behind an explicit repository variable, mirroring self-govern.yml.
// The maker/checker pair is deliberately left to modonome-auto.yml; this file schedules
// only the crew roles that run as single-role invocations.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";
import { topoSort } from "../lib/graph.mjs";
import { loadConfig } from "../validate-config.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");

// The maker/checker pair is the first-class separation-of-duties cycle and runs from
// modonome-auto.yml. self-govern has its own dedicated workflow (self-govern.yml). Both
// are excluded from the schedule generator so it never duplicates an existing workflow.
export const CORE_ROLE_SEQUENCE = ["maker", "checker"];
const RESERVED_ROLES = new Set([...CORE_ROLE_SEQUENCE, "self-govern"]);

// Pinned action refs, identical to modonome-auto.yml and self-govern.yml, so the
// generated workflow keeps the same supply-chain posture and its output is stable.
const CHECKOUT_REF = "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"; // v7.0.0
const SETUP_NODE_REF = "actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e"; // v6.4.0

const WORKFLOW_PATH = ".github/workflows/modonome-schedule.yml";
const GENERATED_BANNER =
  "# GENERATED by scripts/agent/triggers.mjs. DO NOT EDIT.\n" +
  "# Regenerate with: node scripts/agent/triggers.mjs --write\n" +
  "# Source of truth: the schedule and trigger fields under roles in .modonome/config.yaml.";

// Normalize a role's trigger field (string shorthand, object, or absent) into a stable
// shape. A bare string s becomes { type: s }. Absent becomes { type: null }. after and
// cron default to an empty list and null. Pure.
export function normalizeTrigger(trigger) {
  if (typeof trigger === "string") return { type: trigger, after: [], cron: null };
  if (trigger && typeof trigger === "object") {
    return {
      type: typeof trigger.type === "string" ? trigger.type : null,
      after: Array.isArray(trigger.after) ? [...trigger.after] : [],
      cron: typeof trigger.cron === "string" ? trigger.cron : null,
    };
  }
  return { type: null, after: [], cron: null };
}

// Normalize a role's schedule field into { cron, timezone } or null when absent. Pure.
export function normalizeSchedule(schedule) {
  if (schedule && typeof schedule === "object" && typeof schedule.cron === "string") {
    return { cron: schedule.cron, timezone: typeof schedule.timezone === "string" ? schedule.timezone : null };
  }
  return null;
}

// The cron expressions a role fires on: its schedule.cron plus a trigger.cron (or a
// trigger.type of schedule that carries a cron), de-duplicated and sorted for a stable
// render. Returns an empty array for a role with no cadence. Pure.
export function roleCrons(roleCfg) {
  const crons = new Set();
  const sched = normalizeSchedule(roleCfg?.schedule);
  if (sched) crons.add(sched.cron);
  const trig = normalizeTrigger(roleCfg?.trigger);
  if (trig.cron) crons.add(trig.cron);
  return [...crons].sort();
}

// The crew roles the schedule generator manages: every configured role that is not a
// reserved role (maker, checker, self-govern) and has a prompt to run. Sorted for a
// stable render. Pure aside from reading the config object passed in.
export function schedulableCrewRoles(cfg) {
  const roles = cfg?.roles ? Object.keys(cfg.roles) : [];
  return roles.filter((r) => !RESERVED_ROLES.has(r)).sort();
}

// Build the executed role order from after-role triggers. Returns null when no role
// declares trigger.after, so the caller keeps its existing default (a pure maker ->
// checker run) with zero behavior change. When at least one role chains, the order is a
// topological sort over the maker -> checker spine plus every after edge. Throws
// fail-closed on a dangling after target (a role that is not configured) or a cycle,
// before any model call. Pure.
export function deriveTriggerSequence(cfg) {
  const roles = cfg?.roles ? Object.keys(cfg.roles) : [];
  const chaining = roles.filter((r) => normalizeTrigger(cfg.roles[r].trigger).after.length > 0);
  if (chaining.length === 0) return null;

  // adjacency[X] lists roles that must run after X. An edge X -> R means X precedes R.
  const adjacency = {};
  const addEdge = (from, to) => {
    (adjacency[from] ||= []).push(to);
  };
  // Keep the maker -> checker spine when both are present.
  if (roles.includes("maker") && roles.includes("checker")) addEdge("maker", "checker");

  for (const role of chaining) {
    for (const dep of normalizeTrigger(cfg.roles[role].trigger).after) {
      if (!roles.includes(dep)) {
        throw new Error(
          `triggers: role "${role}" declares trigger.after "${dep}", but "${dep}" is not a configured role.`,
        );
      }
      addEdge(dep, role);
    }
  }

  const { order, error } = topoSort(adjacency, roles);
  if (error) throw new Error(`triggers: cannot order roles, ${error}.`);
  return order;
}

// Render one job for a scheduled crew role. It checks out, runs the role as a single
// dry-run invocation of run-cycle.mjs, and only executes behind an explicit repository
// variable. When the role carries one or more crons, the job gates on the matching
// schedule event so each role fires only on its own cadence in the shared workflow.
function renderRoleJob(role, crons) {
  const conditions = [
    ...crons.map((c) => `github.event.schedule == '${c}'`),
    "github.event_name == 'workflow_dispatch'",
  ];
  const guard = conditions.join(" || ");
  return [
    `  ${role}:`,
    `    runs-on: ubuntu-latest`,
    `    if: ${guard}`,
    `    steps:`,
    `      - uses: ${CHECKOUT_REF}   # v7.0.0`,
    `        with:`,
    `          fetch-depth: 0`,
    `      - uses: ${SETUP_NODE_REF}   # v6.4.0`,
    `        with:`,
    `          node-version: '20'`,
    `      - name: Install Claude Code CLI`,
    `        run: npm install -g @anthropic-ai/claude-code`,
    `      - name: Run the ${role} role`,
    `        env:`,
    `          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}`,
    `          MODONOME_ARMED: \${{ secrets.MODONOME_ARMED }}`,
    `          MODONOME_ROLE: ${role}`,
    `        run: |`,
    `          set -o pipefail`,
    `          # Dry-run by default: validates the plan and makes no model call, so it is`,
    `          # green in the off-by-default, zero-budget posture. A live run needs the`,
    `          # owner to arm and fund it: set the MODONOME_SCHEDULE_EXECUTE repository`,
    `          # variable to true and provide a budget and key.`,
    `          MODE="--dry-run"`,
    `          if [ "\${{ vars.MODONOME_SCHEDULE_EXECUTE }}" = "true" ]; then MODE="--execute"; fi`,
    `          node scripts/agent/run-cycle.mjs --roles ${role} "$MODE"`,
  ].join("\n");
}

// Render the full scheduled-crew workflow as a deterministic YAML string. The trigger
// block is the sorted union of every managed role's crons plus workflow_dispatch, so a
// role always has a manual path and fires on its declared cadence. Pure: same config in,
// same bytes out, which is what lets --check detect drift.
export function renderScheduleWorkflow(cfg) {
  const roles = schedulableCrewRoles(cfg);
  const perRoleCrons = new Map(roles.map((r) => [r, roleCrons(cfg.roles[r])]));
  const allCrons = [...new Set(roles.flatMap((r) => perRoleCrons.get(r)))].sort();

  const lines = [];
  lines.push(GENERATED_BANNER);
  lines.push("");
  lines.push("name: Modonome scheduled crew");
  lines.push("");
  lines.push("# Runs each scheduled crew role (a role other than the maker/checker pair and");
  lines.push("# self-govern) on its own cadence. Off by default: every job is a dry-run unless");
  lines.push("# the owner sets MODONOME_SCHEDULE_EXECUTE. The maker/checker loop stays in");
  lines.push("# modonome-auto.yml; this workflow never touches that pair.");
  lines.push("");
  lines.push("on:");
  if (allCrons.length > 0) {
    lines.push("  schedule:");
    for (const c of allCrons) lines.push(`    - cron: '${c}'`);
  }
  lines.push("  workflow_dispatch:");
  lines.push("");
  lines.push("permissions:");
  lines.push("  contents: read");
  lines.push("");
  lines.push("jobs:");
  if (roles.length === 0) {
    // No managed crew role yet. Emit a single inert no-op so the workflow stays valid
    // YAML and the file exists for an operator to see the shape once they add a role.
    lines.push("  noop:");
    lines.push("    runs-on: ubuntu-latest");
    lines.push("    if: github.event_name == 'workflow_dispatch'");
    lines.push("    steps:");
    lines.push("      - name: No scheduled crew roles configured");
    lines.push('        run: echo "No crew roles declare a schedule or trigger yet. Add one under roles in .modonome/config.yaml."');
  } else {
    lines.push(roles.map((r) => renderRoleJob(r, perRoleCrons.get(r))).join("\n\n"));
  }
  return lines.join("\n") + "\n";
}

// Load the repo config through the same loader run-cycle uses, so the generator reads
// exactly what the loop reads. Falls back to an empty roles map when the file is absent.
function loadCfg() {
  try {
    return loadConfig(join(root, ".modonome", "config.yaml")) || { roles: {} };
  } catch {
    return { roles: {} };
  }
}

function main() {
  const argv = process.argv.slice(2);
  if (argv.includes("--self-test")) return selfTest();

  const cfg = loadCfg();
  const rendered = renderScheduleWorkflow(cfg);
  const target = join(root, WORKFLOW_PATH);

  if (argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(target, "utf8");
    } catch {
      current = "";
    }
    if (current !== rendered) {
      console.error(
        `${WORKFLOW_PATH} is out of date with the schedule/trigger config.\n` +
          "Run: node scripts/agent/triggers.mjs --write",
      );
      process.exit(1);
    }
    console.log(`PASS: ${WORKFLOW_PATH} matches the schedule/trigger config.`);
    return;
  }

  if (argv.includes("--write")) {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, rendered);
    console.log(`Wrote ${WORKFLOW_PATH} from the schedule/trigger config.`);
    return;
  }

  process.stdout.write(rendered);
}

function selfTest() {
  const cfg = {
    roles: {
      maker: { model: "claude-sonnet-4-6" },
      checker: { model: "claude-opus-4-8" },
      "self-govern": { model: "claude-haiku-4-5-20251001" },
      researcher: { schedule: { cron: "0 6 * * 1" } },
      envisioner: { trigger: { type: "after-role", after: ["researcher"] } },
    },
  };

  console.assert(normalizeTrigger("schedule").type === "schedule", "string trigger normalizes");
  console.assert(normalizeTrigger(undefined).after.length === 0, "absent trigger normalizes");
  console.assert(roleCrons(cfg.roles.researcher)[0] === "0 6 * * 1", "role cron read");
  console.assert(JSON.stringify(schedulableCrewRoles(cfg)) === JSON.stringify(["envisioner", "researcher"]), "crew roles");

  const seq = deriveTriggerSequence(cfg);
  console.assert(seq.indexOf("maker") < seq.indexOf("checker"), "maker before checker");
  console.assert(seq.indexOf("researcher") < seq.indexOf("envisioner"), "researcher before envisioner");

  console.assert(deriveTriggerSequence({ roles: { maker: {}, checker: {} } }) === null, "no chaining returns null");

  let threwDangling = false;
  try {
    deriveTriggerSequence({ roles: { a: { trigger: { type: "after-role", after: ["ghost"] } } } });
  } catch {
    threwDangling = true;
  }
  console.assert(threwDangling, "dangling after throws");

  let threwCycle = false;
  try {
    deriveTriggerSequence({
      roles: {
        a: { trigger: { type: "after-role", after: ["b"] } },
        b: { trigger: { type: "after-role", after: ["a"] } },
      },
    });
  } catch {
    threwCycle = true;
  }
  console.assert(threwCycle, "cycle throws");

  const wf = renderScheduleWorkflow(cfg);
  console.assert(wf === renderScheduleWorkflow(cfg), "render is deterministic");
  console.assert(wf.includes("Modonome scheduled crew"), "workflow name present");
  console.assert(wf.includes("--dry-run") && wf.includes("MODONOME_SCHEDULE_EXECUTE"), "dry-run default and execute gate");
  console.assert(!wf.includes("maker:") && !wf.includes("checker:"), "core pair excluded");
  console.log("triggers self-test passed.");
}

// Run the CLI only when invoked directly, so importing this module (for
// deriveTriggerSequence, in run-cycle.mjs) has no side effect.
if (import.meta.url === pathToFileURL(process.argv[1] || "").href) {
  main();
}
