// AUTO-GENERATED by a one-off script during migration. Aggregates every
// per-script message-catalog partial into one merged object. Each partial
// lives at message-catalog/<category>/<script-basename>.mjs and exports a
// plain `MESSAGES` object, so a new script's catalog entries can be added as
// a new file with zero risk of merge conflicts with any other script's
// entries.
import { MESSAGES as M_GATE_ASSERT_GOVERNED_CHANGE } from "./gate/assert-governed-change.mjs";
import { MESSAGES as M_GATE_BUILD_POLICY_ATTESTATION } from "./gate/build-policy-attestation.mjs";
import { MESSAGES as M_GATE_CHECK_ARCHITECTURE_DRIFT } from "./gate/check-architecture-drift.mjs";
import { MESSAGES as M_GATE_CHECK_ATTRIBUTION_FP_CORPUS } from "./gate/check-attribution-fp-corpus.mjs";
import { MESSAGES as M_GATE_CHECK_CHECKER_ENGAGEMENT } from "./gate/check-checker-engagement.mjs";
import { MESSAGES as M_GATE_CHECK_CONTROL_PANEL_COHERENCE } from "./gate/check-control-panel-coherence.mjs";
import { MESSAGES as M_GATE_CHECK_CONTROL_PANEL_COVERAGE } from "./gate/check-control-panel-coverage.mjs";
import { MESSAGES as M_GATE_CHECK_DECISIONS_AUTHORITY } from "./gate/check-decisions-authority.mjs";
import { MESSAGES as M_GATE_CHECK_DRIFT } from "./gate/check-drift.mjs";
import { MESSAGES as M_GATE_CHECK_EDIT_SET_COMPLIANCE } from "./gate/check-edit-set-compliance.mjs";
import { MESSAGES as M_GATE_CHECK_EVIDENCE_INTEGRITY } from "./gate/check-evidence-integrity.mjs";
import { MESSAGES as M_GATE_CHECK_EVIDENCE_SECRETS } from "./gate/check-evidence-secrets.mjs";
import { MESSAGES as M_GATE_CHECK_GATE_DAG } from "./gate/check-gate-dag.mjs";
import { MESSAGES as M_GATE_CHECK_LEARNING_TRACEABILITY } from "./gate/check-learning-traceability.mjs";
import { MESSAGES as M_GATE_CHECK_LICENSES } from "./gate/check-licenses.mjs";
import { MESSAGES as M_GATE_CHECK_MD_GOVERNANCE } from "./gate/check-md-governance.mjs";
import { MESSAGES as M_GATE_CHECK_PORTABILITY } from "./gate/check-portability.mjs";
import { MESSAGES as M_GATE_CHECK_PROMOTION_READINESS } from "./gate/check-promotion-readiness.mjs";
import { MESSAGES as M_GATE_CHECK_REGEX_SAFETY } from "./gate/check-regex-safety.mjs";
import { MESSAGES as M_GATE_CHECK_REPO_HYGIENE } from "./gate/check-repo-hygiene.mjs";
import { MESSAGES as M_GATE_CHECK_SELF_APPLICATION } from "./gate/check-self-application.mjs";
import { MESSAGES as M_GATE_CHECK_STATE_MACHINE_ACYCLIC } from "./gate/check-state-machine-acyclic.mjs";
import { MESSAGES as M_GATE_CHECK_STYLE } from "./gate/check-style.mjs";
import { MESSAGES as M_GATE_CHECK_TRUST_BOUNDARY } from "./gate/check-trust-boundary.mjs";
import { MESSAGES as M_GATE_CHECK_WORK_ITEMS } from "./gate/check-work-items.mjs";
import { MESSAGES as M_GATE_GUARD_RATCHET } from "./gate/guard-ratchet.mjs";
import { MESSAGES as M_GATE_RUN_GATE_PIPELINE } from "./gate/run-gate-pipeline.mjs";
import { MESSAGES as M_GATE_TEST_PROMPT_BEHAVIOR } from "./gate/test-prompt-behavior.mjs";
import { MESSAGES as M_GATE_VALIDATE_CONFIG } from "./gate/validate-config.mjs";
import { MESSAGES as M_GATE_VALIDATE_WORK_ITEM } from "./gate/validate-work-item.mjs";
import { MESSAGES as M_AGENT_RUN_OPENAI_CLIENT } from "./agent-run/openai-client.mjs";
import { MESSAGES as M_AGENT_RUN_PROMOTE_LEARNING } from "./agent-run/promote-learning.mjs";
import { MESSAGES as M_AGENT_RUN_QUEUE } from "./agent-run/queue.mjs";
import { MESSAGES as M_AGENT_RUN_RELEASE } from "./agent-run/release.mjs";
import { MESSAGES as M_AGENT_RUN_RENDER_PROMPT } from "./agent-run/render-prompt.mjs";
import { MESSAGES as M_AGENT_RUN_TOOL_LOOP_ADAPTER } from "./agent-run/tool-loop-adapter.mjs";
import { MESSAGES as M_AGENT_RUN_TRANSITION_WORK_ITEM } from "./agent-run/transition-work-item.mjs";
import { MESSAGES as M_ADVISORY_DETECT_NEAR_MISS } from "./advisory/detect-near-miss.mjs";

export const CATALOG_PARTIALS = [
  M_GATE_ASSERT_GOVERNED_CHANGE,
  M_GATE_BUILD_POLICY_ATTESTATION,
  M_GATE_CHECK_ARCHITECTURE_DRIFT,
  M_GATE_CHECK_ATTRIBUTION_FP_CORPUS,
  M_GATE_CHECK_CHECKER_ENGAGEMENT,
  M_GATE_CHECK_CONTROL_PANEL_COHERENCE,
  M_GATE_CHECK_CONTROL_PANEL_COVERAGE,
  M_GATE_CHECK_DECISIONS_AUTHORITY,
  M_GATE_CHECK_DRIFT,
  M_GATE_CHECK_EDIT_SET_COMPLIANCE,
  M_GATE_CHECK_EVIDENCE_INTEGRITY,
  M_GATE_CHECK_EVIDENCE_SECRETS,
  M_GATE_CHECK_GATE_DAG,
  M_GATE_CHECK_LEARNING_TRACEABILITY,
  M_GATE_CHECK_LICENSES,
  M_GATE_CHECK_MD_GOVERNANCE,
  M_GATE_CHECK_PORTABILITY,
  M_GATE_CHECK_PROMOTION_READINESS,
  M_GATE_CHECK_REGEX_SAFETY,
  M_GATE_CHECK_REPO_HYGIENE,
  M_GATE_CHECK_SELF_APPLICATION,
  M_GATE_CHECK_STATE_MACHINE_ACYCLIC,
  M_GATE_CHECK_STYLE,
  M_GATE_CHECK_TRUST_BOUNDARY,
  M_GATE_CHECK_WORK_ITEMS,
  M_GATE_GUARD_RATCHET,
  M_GATE_RUN_GATE_PIPELINE,
  M_GATE_TEST_PROMPT_BEHAVIOR,
  M_GATE_VALIDATE_CONFIG,
  M_GATE_VALIDATE_WORK_ITEM,
  M_AGENT_RUN_OPENAI_CLIENT,
  M_AGENT_RUN_PROMOTE_LEARNING,
  M_AGENT_RUN_QUEUE,
  M_AGENT_RUN_RELEASE,
  M_AGENT_RUN_RENDER_PROMPT,
  M_AGENT_RUN_TOOL_LOOP_ADAPTER,
  M_AGENT_RUN_TRANSITION_WORK_ITEM,
  M_ADVISORY_DETECT_NEAR_MISS,
];
